package com.counterweight.inventory.domain

import jakarta.persistence.*
import org.hibernate.annotations.Formula
import org.hibernate.annotations.Generated
import org.hibernate.generator.EventType
import java.math.BigDecimal
import java.time.Instant

/**
 * A physical count.
 *
 * The shop counts what is on the shelf and the system says what it believed was
 * there; the gap between them is the only honest measure of shrinkage a
 * business like this gets. §5 makes it work: because stock is an append-only
 * ledger and balances are derived, a count reconciles by posting one more
 * movement rather than by overwriting a number and losing the evidence.
 *
 * A count does **not** stop trading. [scopePath] narrows it to a category
 * subtree so the agro-chemical shelf can be counted while the hardware side
 * keeps selling — which is the only version of this a one-room shop will
 * actually do.
 */
@Entity
@Table(name = "stock_take")
class StockTake(
    @Column(name = "branch_id", nullable = false)
    var branchId: Long,

    @Column(nullable = false)
    var reference: String,

    @Column(name = "opened_by", nullable = false)
    var openedBy: Long,
) {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null

    /**
     * The category subtree being counted, as an ltree path. Null counts
     * everything.
     *
     * Read through a formula for the same reason `Category.path` is: `ltree`
     * reports as `Types#OTHER` over JDBC and `ddl-auto: validate` refuses to
     * start against a String property. The value is set through a native
     * statement at open, so nothing binds it as a parameter either.
     */
    @Formula("scope_path::text")
    var scopePath: String? = null

    @Column(nullable = false)
    var status: String = OPEN

    @Column(name = "opened_at", nullable = false, updatable = false)
    var openedAt: Instant = Instant.now()

    @Column(name = "posted_by")
    var postedBy: Long? = null

    @Column(name = "posted_at")
    var postedAt: Instant? = null

    val isOpen: Boolean get() = status == OPEN || status == COUNTED

    override fun equals(other: Any?) = this === other || (other is StockTake && id != null && id == other.id)
    override fun hashCode() = javaClass.hashCode()
    override fun toString() = "StockTake($reference)"

    companion object {
        /** Lines snapshotted, counting under way. */
        const val OPEN = "OPEN"

        /** Every line has a figure against it and it is ready to be signed off. */
        const val COUNTED = "COUNTED"

        /** Variances are in the ledger. Terminal — a posted count is history. */
        const val POSTED = "POSTED"

        /** Abandoned. Nothing was posted, and the snapshot stays as evidence it happened. */
        const val CANCELLED = "CANCELLED"
    }
}

/**
 * One lot on the count sheet.
 *
 * [expectedQty] is frozen when counting begins, not read at post time. That is
 * what makes the variance mean something while the shop is still trading: it
 * answers "what did the books say when we started", and the sales that happened
 * during the count are already in the ledger explaining themselves.
 *
 * [countedQty] is null until somebody has actually looked. Null is not zero,
 * and the difference matters enormously — treating an uncounted lot as zero
 * would write off the whole shelf.
 */
@Entity
@Table(name = "stock_take_line")
class StockTakeLine(
    @Column(name = "stock_take_id", nullable = false)
    var stockTakeId: Long,

    @Column(name = "lot_id", nullable = false)
    var lotId: Long,

    @Column(name = "expected_qty", nullable = false)
    var expectedQty: BigDecimal,
) {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null

    @Column(name = "counted_qty")
    var countedQty: BigDecimal? = null

    /**
     * counted − expected, generated by the database.
     *
     * [Generated] so it can be read back in the transaction that wrote the
     * count; without it Hibernate keeps the stale in-memory value and the
     * variance reads null on the one screen that exists to show it.
     */
    @Generated(event = [EventType.INSERT, EventType.UPDATE])
    @Column(name = "variance", insertable = false, updatable = false)
    var variance: BigDecimal? = null

    var note: String? = null

    val isCounted: Boolean get() = countedQty != null

    override fun equals(other: Any?) = this === other || (other is StockTakeLine && id != null && id == other.id)
    override fun hashCode() = javaClass.hashCode()
}
